import { Router } from 'express';
import authRoutes from './auth';
import orderRoutes from './orders';
import customerRoutes from './customers';
import productRoutes from './products';
import userRoutes from './users';
import analyticsRoutes from './analytics';
import webhookRoutes from './webhook';
import notificationRoutes from './notifications';
import exportRoutes from './export';
import integrationRoutes from './integrations';
import eventsRoutes from './events';
import novaPoshtaRoutes from './nova-poshta';
import callbackRoutes from './callbacks';
import telegramRoutes from './telegram';
import organizationRoutes from './organization';
import searchRoutes from './search';
import orderTemplateRoutes from './orderTemplates';
import importRoutes from './import';
import achievementRoutes from './achievements';
import goalsRoutes from './goals';
import orderViewsRoutes from './orderViews';
import cronRoutes from './cron';

const router = Router();

router.use('/auth', authRoutes);
router.use('/events', eventsRoutes);
router.use('/orders', orderRoutes);
router.use('/customers', customerRoutes);
router.use('/products', productRoutes);
router.use('/users', userRoutes);
router.use('/analytics', analyticsRoutes);
router.use('/webhook', webhookRoutes);
router.use('/notifications', notificationRoutes);
router.use('/export', exportRoutes);
router.use('/integrations', integrationRoutes);
router.use('/nova-poshta', novaPoshtaRoutes);
router.use('/callbacks', callbackRoutes);
router.use('/telegram', telegramRoutes);
router.use('/organization', organizationRoutes);
router.use('/search', searchRoutes);
router.use('/order-templates', orderTemplateRoutes);
router.use('/import', importRoutes);
router.use('/achievements', achievementRoutes);
router.use('/goals', goalsRoutes);
router.use('/order-views', orderViewsRoutes);
router.use('/cron', cronRoutes);

export default router;
